#comments
server:
  port: 9797
  contextPath: /SpringBootCRUDApp

spring:
  profiles: local, default
datasource:
   sampleapp:
    url: jdbc:oracle:thin:@localhost:1521:XE
    username: system
    password: admin
    driverClassName: oracle.jdbc.driver.OracleDriver
    defaultSchema:
    maxPoolSize: 20
    hibernate:
      hbm2ddl.method: update
      show_sql: true
      format_sql: true
      dialect: org.hibernate.dialect.Oracle10gDialect


